[versions]
activity-compose = "1.8.1"
agp = "8.3.0-alpha17"
androidx-core-ktx = "1.12.0"
coil-compose = "2.5.0"
fuel-kotlinx-serialization = "3.0.0-alpha1"
kotlinx-datetime = "0.5.0"
jetbrains-compose = "1.5.11"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }
fuel-kotlinx-serialization = { group = "com.github.kittinunf.fuel", name = "fuel-kotlinx-serialization", version.ref = "fuel-kotlinx-serialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }